# Generated by Django 5.2.9 on 2025-12-20 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
    ]
