# Generated by Django 5.2.9 on 2025-12-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_deleted',
        ),
    ]
